name: Run PSPSScriptAnalyzer on PowerShell Scripts

on:
  push:
    branches: [ main ]

jobs:
  PSScriptAnalyzer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get Changed Files
        id: changed-files
        run: |
          # Get a list of changed files in the latest commit
          git diff --name-only HEAD^..HEAD^1 > changed_files.txt

      - name: Run PSScriptAnalyzer on Changed Files
        shell: pwsh
        run: |
          # Read the list of changed files
          $changedFiles = Get-Content changed_files.txt

          # Scan only the modified files
          foreach ($file in $changedFiles) {
            Invoke-ScriptAnalyzer -Path $file -Severity Warning -EnableExit
          }
