name: Run PSPSScriptAnalyzer on PowerShell Scripts

on:
  push:
    branches: [ main ]

jobs:
  PSScriptAnalyzer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get Changed Files
        id: changed-files
        run: |
          git log -1 --name-only --pretty=format: | tail -n +2 > changed_files.txt

      - name: Unzip ZIP files
        run: |
          # Assuming your ZIP files are in a directory called "zipped"
          mkdir unzipped
          find . -type f -name "*.zip" -exec unzip -o {} -d unzipped \;

      - name: Run PSScriptAnalyzer on Changed Files
        shell: pwsh
        run: |
          $changedFiles = Get-Content changed_files.txt
          foreach ($file in $changedFiles) {
            # Assuming the extracted files are in the "unzipped" directory
            Invoke-ScriptAnalyzer -Path "unzipped/$file" -Severity Warning -EnableExit
          }
