name: Run PSPSScriptAnalyzer on PowerShell Scripts

on:
  push:
    branches: [ main ]

jobs:
  PSScriptAnalyzer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get Changed Files
        id: changed-files
        run: |
          git log -1 --name-only --pretty=format: | tail -n +2 > changed_files.txt

      - name: Unzip ZIP files
        run: |
          mkdir unzipped
          find zipped -type f -name "*.zip" -exec unzip -o {} -d unzipped \;

      - name: Run PSScriptAnalyzer on Changed Files
        shell: pwsh
        run: |
          $changedFiles = Get-Content changed_files.txt
          foreach ($file in $changedFiles) {
            # Assuming the extracted files are in the "unzipped" directory
            $filePath = "unzipped/zipped/$file"
            if (Test-Path $filePath) {
              Invoke-ScriptAnalyzer -Path $filePath -Severity Warning -EnableExit
            } else {
              Write-Host "File not found: $filePath"
            }
          }
